/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.otus;

import com.google.common.collect.Lists;

import java.util.ArrayList;
import java.util.List;


/**
 *
 * To start the application:
 * ./gradlew build
 * java -jar ./L01-gradle/build/libs/gradleHelloWorld-0.1.jar
 *
 * To unzip the jar:
 * unzip -l L01-gradle.jar
 * unzip -l gradleHelloWorld-0.1.jar
 *
 */
public class App {
    public static void main(String... args) {
        System.out.println(HelloOtus.foo(null, "Not null two"));
        System.out.println(HelloOtus.foo("Not null one", "Not null two"));
    }
}
